import { pgTable, uuid, text, timestamp } from 'drizzle-orm/pg-core';

/**
 * GeneratedSentence Entity
 *
 * Tracks unique sentences generated by combining 2-4 related words for mixed practice.
 * Uses wordIdsHash to prevent repeating the same word combination.
 *
 * Reference: /docs/engineering/implementation_plan.md (lines 164-176)
 */
export const generatedSentences = pgTable('generated_sentences', {
  // Primary Key
  id: uuid('id').primaryKey().defaultRandom(),

  // Foreign Keys
  userId: uuid('user_id').notNull(), // References auth.users (Supabase Auth)
  sessionId: uuid('session_id'), // References review_sessions (null if pre-generated but not yet used)

  // Sentence Content
  text: text('text').notNull(), // The generated sentence (max 10 words)
  audioUrl: text('audio_url'), // Sentence audio URL

  // Word Tracking
  wordIds: uuid('word_ids').array().notNull(), // Array of 2-4 word IDs combined in this sentence
  wordIdsHash: text('word_ids_hash').notNull().unique(), // Sorted wordIds hash for fast dedup lookup

  // Exercise Configuration
  exerciseType: text('exercise_type', {
    enum: ['type_translation', 'fill_blank', 'multiple_choice']
  }).notNull(),

  // Usage Tracking
  usedAt: timestamp('used_at'), // null = pre-generated but not yet shown
  createdAt: timestamp('created_at').notNull().defaultNow(),
});

export type GeneratedSentence = typeof generatedSentences.$inferSelect;
export type NewGeneratedSentence = typeof generatedSentences.$inferInsert;
